// src/routes/badges.svelte
<script></script>

<b-container style="padding-top: 60px">
  <b-row>
    <b-col class="mt-3 ml-0 mr-0" cols="12">
      <b-row class="mt-2 mb-0 ml-0 mr-0">
        <h3>Badges</h3>
      </b-row>
      <b-row class="mt-2 mb-0 ml-0 mr-0" />
      <b-row class="mt-2 mb-4 ml-0 mr-0">
        <b-col class="ml-0 mr-0">
          <b-row class="ml-0">
            <p>
              <img
                alt="GitHub all releases"
                src="https://img.shields.io/github/downloads/GMLC-TDC/helics/total"
              />
              <br />&raquo;
              <img
                alt="GitHub issues"
                src="https://img.shields.io/github/issues-raw/GMLC-TDC/HELICS"
              />
              <br />&raquo;
              <img
                alt="GitHub closed issues"
                src="https://img.shields.io/github/issues-closed-raw/GMLC-TDC/HELICS"
              />
              <br />&raquo;
              <img
                alt="GitHub pull requests"
                src="https://img.shields.io/github/issues-pr-raw/GMLC-TDC/HELICS"
              />
              <br />&raquo;
              <img
                alt="GitHub closed pull requests"
                src="https://img.shields.io/github/issues-pr-closed-raw/GMLC-TDC/HELICS"
              />
              <br />&raquo;
              <img
                alt="GitHub contributors"
                src="https://img.shields.io/github/contributors-anon/GMLC-TDC/HELICS"
              />
              <br />&raquo;
            </p>
          </b-row>
        </b-col>
      </b-row>
    </b-col>
  </b-row>
</b-container>

<style>
  img {
    max-width: 240px;
    max-height: 200px;
    width: auto;
    height: auto;
  }
  h5 {
    text-decoration: underline;
  }
</style>

// pages/badges.vue
<template>
  <b-container style="padding-top: 60px">
    <b-row>
      <b-col class="mt-3 ml-0 mr-0" cols="12">
        <b-row class="mt-2 mb-0 ml-0 mr-0">
          <h3>Badges</h3>
        </b-row>
        <b-row class="mt-2 mb-0 ml-0 mr-0"> </b-row>
        <b-row class="mt-2 mb-4 ml-0 mr-0">
          <b-col class="ml-0 mr-0">
            <b-row class="ml-0">
              <p>
                <img
                  alt="GitHub all releases"
                  src="https://img.shields.io/github/downloads/GMLC-TDC/helics/total"
                />
                <br />&raquo;
                <img
                  alt="GitHub issues"
                  src="https://img.shields.io/github/issues-raw/GMLC-TDC/HELICS"
                />
                <br />&raquo;
                <img
                  alt="GitHub closed issues"
                  src="https://img.shields.io/github/issues-closed-raw/GMLC-TDC/HELICS"
                />
                <br />&raquo;
                <img
                  alt="GitHub pull requests"
                  src="https://img.shields.io/github/issues-pr-raw/GMLC-TDC/HELICS"
                />
                <br />&raquo;
                <img
                  alt="GitHub closed pull requests"
                  src="https://img.shields.io/github/issues-pr-closed-raw/GMLC-TDC/HELICS"
                />
                <br />&raquo;
                <img
                  alt="GitHub contributors"
                  src="https://img.shields.io/github/contributors-anon/GMLC-TDC/HELICS"
                />
                <br />&raquo;
              </p>
            </b-row>
          </b-col>
        </b-row>
      </b-col>
    </b-row>
  </b-container>
</template>

<script></script>

<style>
img {
  max-width: 240px;
  max-height: 200px;
  width: auto;
  height: auto;
}
h5 {
  text-decoration: underline;
}
</style>
